name: go-cleanarch
on:
  pull_request:
    branches:
      - main
      - development

jobs:
  go-cleanarch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
          cache: true

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/537156000473/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'github-identity-pool@devops-339608.iam.gserviceaccount.com'

      - uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: 'ffc-platform-development'

      - uses: pocket-apps/action-setup-firebase@v2
        with:
          firebase-token: "shake" # Don't need this, but it's mandatory that its set so...

      - name: Setup github for go private
        run: git config --global url.https://${{ secrets.SERVICE_HASTINGS_PAT }}@github.com/.insteadOf https://github.com/

      - name: Install dependencies
        run: |
          go version
          go install github.com/roblaszczak/go-cleanarch

      - name: Run linter
        run: go-cleanarch ./pkg -ignore-tests -domain entities -application usecases -interfaces adapters -infrastructure drivers
