name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - development
      - main
  pull_request:
    branches:
      - main
      - development
permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
          cache: true

      - name: Setup github for go private
        run: git config --global url.https://${{ secrets.SERVICE_HASTINGS_PAT }}@github.com/.insteadOf https://github.com/

      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.0
      
      - name: run golangci-lint
        run: golangci-lint run ./cmd ./pkg/... --version -v --out=github-actions -v --timeout=30m
